### ISSUE TITLE
Integrate Continuous Data Flow to IDAS with NodeRED

### ISSUE THREAD

**Issue by GregorFernbach** [AnotherCodeArtist/CEPWare#7]
Implement a continuous data flow to the IDAS component by using NodeRED

**Comment by sweiland** [comment]
Rudimentary implementation: Every second for the first 20s, 20C is reported from a randomly chosen room. After that, temperatures increase for 30s at 1C/s. Then the sensor "burns" and starts reporting random numbers.

**Comment by sweiland** [comment]
no nodered anymore, written in Go. Pretty much simplest implementation, but works.
